import { FAQItem, HeroButton, ParallaxImage, TeamMember } from "./types";

export const parallaxImages: ParallaxImage[] = [
    {
      src: '/assets/hero/image1.svg',
      alt: 'Construction workers',
      position: 'top-left',
      width: 'w-72',
      speed: 0.15,
    },
    {
      src: '/assets/hero/image2.svg',
      alt: 'Business meeting',
      position: 'top-right',
      width: 'w-80',
      speed: 0.25,
    },
    {
      src: '/assets/hero/image3.svg',
      alt: 'Office workspace',
      position: 'bottom-left',
      width: 'w-1/3',
      speed: 0.2,
    },
    {
      src: '/assets/hero/image4.svg',
      alt: 'Engineering work',
      position: 'bottom-right',
      width: 'w-80',
      speed: 0.3,
    },
  ];
  
  export const mainButtons: HeroButton[] = [
    {
      text: 'Explore Divisions',
      href: '/divisions',
      variant: 'primary',
    },
    {
      text: 'Get in touch',
      href: '/contact',
      variant: 'secondary',
    },
  ];

  export const divisionButtons: HeroButton[] = [
    {
      text: 'Explore Projects',
      href: '/projects',
      variant: 'primary',
    },
    {
      text: 'Get in touch',
      href: '/contact',
      variant: 'secondary',
    },
  ];

  export const teamMembers: TeamMember[] = [
    {
      id: 'Dr-Joshua',
      name: 'Dr Joshua Olorunkiya (PhD.)',
      role: 'CEO',
      image: '/assets/teams/drjoshua.webp',
      bio: 'Expert in sustainable development with 10+ years of experience in green energy solutions.',
      email: 'jenny.wilson@esthoj.com',
      linkedin: 'https://linkedin.com/in/jennywilson',
    },
  ];

  export const projectsList = [
    {
      slug: 'citec',
      title: "Private Client Luxury TD Interior",
      date: "25th February, 2025",
      description: 'Design and Build project for a luxury TD interior',
      images: [
        "/assets/projects/citec/image1.webp",
        "/assets/projects/citec/image2.webp",
        "/assets/projects/citec/image3.webp",
        "/assets/projects/citec/image4.webp",
        "/assets/projects/citec/image5.webp",
        "/assets/projects/citec/image6.webp",
        "/assets/projects/citec/image7.webp",
        "/assets/projects/citec/image8.webp",
        "/assets/projects/citec/image9.webp",
        "/assets/projects/citec/image10.webp",
        "/assets/projects/citec/image11.webp",
        "/assets/projects/citec/image12.webp",
        "/assets/projects/citec/image13.webp",
        "/assets/projects/citec/image14.webp",
        "/assets/projects/citec/image15.webp",
        "/assets/projects/citec/image16.webp",
        "/assets/projects/citec/image17.webp",
        "/assets/projects/citec/image18.webp",
        "/assets/projects/citec/image19.webp",
        "/assets/projects/citec/image20.webp",
        "/assets/projects/citec/image21.webp",
        "/assets/projects/citec/image22.webp",
      ],
    },
   
    {
      slug: 'ph-mansion',
      title: "Port Harcourt Mansion",
      date: "13th April, 2025",
      description: 'A grand luxury residence featuring neoclassical architectural design, highlighted by tall Corinthian columns, a marble-finished fountain court, and refined exterior detailing that reflects elegance and craftsmanship.',
      images: [
        "/assets/projects/phmansion/image1.webp",
        "/assets/projects/phmansion/image2.webp",
        "/assets/projects/phmansion/image3.webp",
        "/assets/projects/phmansion/image4.webp",
        "/assets/projects/phmansion/image5.webp",
        "/assets/projects/phmansion/image6.webp",
      ],
    },
    {
      slug: "ethanol-factory-ologbo",
      title: "Ethanol Factory Ologbo, Edo State",
      date: "13th April, 2025",
      description: 'A multi-level industrial processing plant featuring heavy-duty structural steel, integrated piping systems, and engineered platforms designed for safe and efficient industrial operations.',
      images: [
         "/assets/projects/ethanolFactory/image1.webp",
         "/assets/projects/ethanolFactory/image2.webp",
         "/assets/projects/ethanolFactory/image3.webp",
         "/assets/projects/ethanolFactory/image4.webp",
         "/assets/projects/ethanolFactory/image5.webp",
         "/assets/projects/ethanolFactory/image6.webp",
         "/assets/projects/ethanolFactory/image7.webp",
        ]
    },
    {
      slug: 'renewed-hope-projects',
      title: "Renewed Hope Project Abuja",
      date: "13th April, 2025",
      description: 'A residential estate featuring a mix of 2-bedroom and 3-bedroom units, designed to provide comfortable and functional living spaces for families and individuals.',
      images: [
        "/assets/projects/renewedHope/image1.webp",
        "/assets/projects/renewedHope/image2.webp",
        "/assets/projects/renewedHope/image3.webp",
      ],
    },
    {
      slug: 'hotr',
      title: "House on the Rock",
      date: "13th April, 2025",
      description: '',
      images: [
        "/assets/projects/hotr/image1.webp",
        "/assets/projects/hotr/image2.webp",
        "/assets/projects/hotr/image3.webp",
        "/assets/projects/hotr/image4.webp",
      ],
    },
    // Add more projects for the full projects page
    {
      slug: 'enclave-estate-asokoro',
      title: "Enclave Estate Asokoro, Abuja",
      date: "10th March, 2025",
      description: 'A residential estate featuring a mix of 2-bedroom and 3-bedroom units, designed to provide comfortable and functional living spaces for families and individuals.',
      images: [
        "/assets/projects/enclave/image1.webp",
        "/assets/projects/enclave/image2.webp",
        "/assets/projects/enclave/image3.webp",
        "/assets/projects/enclave/image4.webp",
        "/assets/projects/enclave/image5.webp",
        "/assets/projects/enclave/image6.webp",
        "/assets/projects/enclave/image7.webp",
        "/assets/projects/enclave/image8.webp",
        "/assets/projects/enclave/image9.webp",
        "/assets/projects/enclave/image10.webp",
        "/assets/projects/enclave/image11.webp",
        "/assets/projects/enclave/image12.webp",
        "/assets/projects/enclave/image13.webp",
        "/assets/projects/enclave/image14.webp",
        "/assets/projects/enclave/image15.webp",
      ],
    },
    {
      slug: 'bua',
      title: "BUA Project",
      date: "25th February, 2025",
      description: 'A residential estate featuring a mix of 2-bedroom and 3-bedroom units, designed to provide comfortable and functional living spaces for families and individuals.',
      images: [
        "/assets/projects/bua/image1.webp",
        "/assets/projects/bua/image2.webp",
        "/assets/projects/bua/image3.webp",
        "/assets/projects/bua/image4.webp",
      ],
    },
    {
      slug: 'abia',
      title: "Abia Project",
      date: "25th February, 2025",
      description: 'A residential estate featuring a mix of 2-bedroom and 3-bedroom units, designed to provide comfortable and functional living spaces for families and individuals.',
      images: [
        "/assets/projects/abia1/image1.webp",
        "/assets/projects/abia1/image2.webp",
        "/assets/projects/abia1/image3.webp",
        "/assets/projects/abia1/image4.webp",
        "/assets/projects/abia1/image5.webp",
        "/assets/projects/abia1/image6.webp",
        "/assets/projects/abia1/image7.webp",
        "/assets/projects/abia1/image8.webp",
      ],
    },
    {
      slug: 'bima',
      title: "Bima Project",
      date: "25th February, 2025",
      description: 'A residential estate featuring a mix of 2-bedroom and 3-bedroom units, designed to provide comfortable and functional living spaces for families and individuals.',
      images: [
        "/assets/projects/bima/image1.webp",
        "/assets/projects/bima/image2.webp",
        "/assets/projects/bima/image3.webp",
        "/assets/projects/bima/image4.webp",
        "/assets/projects/bima/image5.webp",
        "/assets/projects/bima/image6.webp",
        "/assets/projects/bima/image7.webp",
        "/assets/projects/bima/image8.webp",
        "/assets/projects/bima/image9.webp",
        "/assets/projects/bima/image10.webp",
        "/assets/projects/bima/image11.webp",
        "/assets/projects/bima/image12.webp",
        "/assets/projects/bima/image13.webp",
        "/assets/projects/bima/image14.webp",
        "/assets/projects/bima/image15.webp",
        "/assets/projects/bima/image16.webp",
      ],

    },
    {
      slug: 'new_citec',
      title: "Private Client 4B Duplex 3D",
      date: "25th February, 2025",
      description: 'Private Client 4B Duplex 3D',
      images: [
        "/assets/projects/new_citec/image1.webp",
        "/assets/projects/new_citec/image2.webp",
        "/assets/projects/new_citec/image3.webp",
        "/assets/projects/new_citec/image4.webp",
        "/assets/projects/new_citec/image5.webp",
        "/assets/projects/new_citec/image6.webp",
        "/assets/projects/new_citec/image7.webp",
        "/assets/projects/new_citec/image8.webp",
        "/assets/projects/new_citec/image9.webp",
        "/assets/projects/new_citec/image10.webp",
        "/assets/projects/new_citec/image11.webp",
        "/assets/projects/new_citec/image12.webp",
      ],
    },
    {
      slug: 'citec_luxury',
      title: "Private Client Luxury Terrance Duplex 3D ",
      date: "25th February, 2025",
      description: 'Private Client 4B Duplex 3D',
      images: [
        "/assets/projects/citex_luxury/image1.webp",
        "/assets/projects/citex_luxury/image2.webp",
        "/assets/projects/citex_luxury/image3.webp",
        "/assets/projects/citex_luxury/image4.webp",
        "/assets/projects/citex_luxury/image5.webp",
        "/assets/projects/citex_luxury/image6.webp",
        "/assets/projects/citex_luxury/image7.webp",
        "/assets/projects/citex_luxury/image8.webp",
        "/assets/projects/citex_luxury/image9.webp",
        "/assets/projects/citex_luxury/image10.webp",
        "/assets/projects/citex_luxury/image11.webp",
        "/assets/projects/citex_luxury/image12.webp",
        "/assets/projects/citex_luxury/image13.webp",
      ],
    },
    {
      slug: 'facade',
      title: "Private Client",
      date: "25th February, 2025",
      description: 'Private Client project',
      images: [
        "/assets/projects/facade/image1.webp",
        "/assets/projects/facade/image2.webp",
        "/assets/projects/facade/image3.webp",
        "/assets/projects/facade/image4.webp",
        "/assets/projects/facade/image5.webp",
        "/assets/projects/facade/image6.webp",
        "/assets/projects/facade/image7.webp",
        "/assets/projects/facade/image8.webp",
        "/assets/projects/facade/image9.webp",
        "/assets/projects/facade/image10.webp",
        "/assets/projects/facade/image11.webp",
        "/assets/projects/facade/image12.webp",
      ],
    },
    {
      slug: 'mtn-enugu',
      title: "MTN Regional Office , Kano and Port Harcourt",
      date: "25th February, 2025",
      description: 'MTN Regional Office , Kano and Port Harcourt',
      images: [
        "/assets/projects/mtn-enugu/image1.webp",
        "/assets/projects/mtn-enugu/image2.webp",
        "/assets/projects/mtn-enugu/image3.webp",
        "/assets/projects/mtn-enugu/image4.webp",
        "/assets/projects/mtn-enugu/image5.webp",
        "/assets/projects/mtn-enugu/image6.webp",
        "/assets/projects/mtn-enugu/image7.webp",
        "/assets/projects/mtn-enugu/image9.webp",
        "/assets/projects/mtn-enugu/image10.webp",
      ],
    },
    {
      slug: 'panda-agric',
      title: "Panda Agric Project",
      date: "25th February, 2025",
      description: 'Panda Agric Project',
      images: [
        "/assets/projects/panda-agric/image1.webp",
        "/assets/projects/panda-agric/image2.webp",
        "/assets/projects/panda-agric/image3.webp",
        "/assets/projects/panda-agric/image4.webp",
        "/assets/projects/panda-agric/image5.webp",
        "/assets/projects/panda-agric/image7.webp",
        "/assets/projects/panda-agric/image8.webp",
        "/assets/projects/panda-agric/image9.webp",
        "/assets/projects/panda-agric/image10.webp",
        "/assets/projects/panda-agric/image11.webp",
        "/assets/projects/panda-agric/image13.webp",
      ],
    },

    {
      slug: 'akure-hotel',
      title: "BON Hotel, Akure",
      date: "25th February, 2025",
      description: 'BON Hotel, Akure',
      images: [
        "/assets/projects/akure-hotel/image1.webp",
        "/assets/projects/akure-hotel/image2.webp",
        "/assets/projects/akure-hotel/image3.webp",
        "/assets/projects/akure-hotel/image4.webp",
        "/assets/projects/akure-hotel/image5.webp",
        "/assets/projects/akure-hotel/image6.webp",
        "/assets/projects/akure-hotel/image7.webp",
        "/assets/projects/akure-hotel/image8.webp",
        "/assets/projects/akure-hotel/image9.webp",
        "/assets/projects/akure-hotel/image10.webp",
        "/assets/projects/akure-hotel/image11.webp",
        "/assets/projects/akure-hotel/image13.webp",
        "/assets/projects/akure-hotel/image17.webp",
        "/assets/projects/akure-hotel/image18.webp",
        "/assets/projects/akure-hotel/image20.webp",
        "/assets/projects/akure-hotel/image22.webp",
        "/assets/projects/akure-hotel/image23.webp",
        "/assets/projects/akure-hotel/image24.webp",
        "/assets/projects/akure-hotel/image25.webp",
        "/assets/projects/akure-hotel/image26.webp",
      ],
    },

    {
      slug: 'cbn',
      title: "Private Client",
      date: "25th February, 2025",
      description: 'Private Client project',
      images: [
        "/assets/projects/cbn/image1.webp",
        "/assets/projects/cbn/image2.webp",
        "/assets/projects/cbn/image3.webp",
        "/assets/projects/cbn/image4.webp",
        "/assets/projects/cbn/image5.webp",
        "/assets/projects/cbn/image6.webp",
        "/assets/projects/cbn/image7.webp",
        "/assets/projects/cbn/image8.webp",
        "/assets/projects/cbn/image9.webp",
        "/assets/projects/cbn/image10.webp",
      ],
    },

    {
      slug: 'lagos-tower-project',
      title: "Private Client",
      date: "25th February, 2025",
      description: 'Private Client project',
      images: [
        "/assets/projects/lagos-tower-project/image1.webp",
        "/assets/projects/lagos-tower-project/image2.webp",
        "/assets/projects/lagos-tower-project/image3.webp",
        "/assets/projects/lagos-tower-project/image4.webp",
        "/assets/projects/lagos-tower-project/image5.webp",
        "/assets/projects/lagos-tower-project/image7.webp",
        "/assets/projects/lagos-tower-project/image8.webp",
        "/assets/projects/lagos-tower-project/image9.webp",
        "/assets/projects/lagos-tower-project/image10.webp",
        "/assets/projects/lagos-tower-project/image11.webp",
        "/assets/projects/lagos-tower-project/image13.webp",
        "/assets/projects/lagos-tower-project/image14.webp",
      ],
    },

    // nedd to add the rest of the picture 

    {
      slug: 'mtn-durumi',
      title: "MTN Switch Durum",
      date: "25th February, 2025",
      description: 'MTN Switch Durumi',
      images: [
        "/assets/projects/mtn-durumi/image1.webp",
        "/assets/projects/mtn-durumi/image2.webp",
        "/assets/projects/mtn-durumi/image3.webp",
        "/assets/projects/mtn-durumi/image4.webp",
        "/assets/projects/mtn-durumi/image5.webp",
        "/assets/projects/mtn-durumi/image6.webp",
        "/assets/projects/mtn-durumi/image7.webp",
        "/assets/projects/mtn-durumi/image8.webp",
        "/assets/projects/mtn-durumi/image9.webp",
        "/assets/projects/mtn-durumi/image10.webp",
        "/assets/projects/mtn-durumi/image11.webp",
        "/assets/projects/mtn-durumi/image12.webp",
        "/assets/projects/mtn-durumi/image13.webp",
        "/assets/projects/mtn-durumi/image14.webp",
        "/assets/projects/mtn-durumi/image15.webp",
        "/assets/projects/mtn-durumi/image16.webp",
      ],

    },

    {
      slug: 'ph-mtn-center',
      title: "MTN PH  Experience Centre",
      date: "25th February, 2025",
      description: 'MTN PH  Experience Centre',
      images: [
        "/assets/projects/ph-mtn-center/image1.webp",
        "/assets/projects/ph-mtn-center/image2.webp",
        "/assets/projects/ph-mtn-center/image3.webp",
        "/assets/projects/ph-mtn-center/image4.webp",
        "/assets/projects/ph-mtn-center/image5.webp",
        "/assets/projects/ph-mtn-center/image7.webp",
        "/assets/projects/ph-mtn-center/image8.webp",
        "/assets/projects/ph-mtn-center/image9.webp",
        "/assets/projects/ph-mtn-center/image10.webp",
        "/assets/projects/ph-mtn-center/image11.webp",
        "/assets/projects/ph-mtn-center/image13.webp",
        "/assets/projects/ph-mtn-center/image14.webp",
      ],
    },
    

  ];



  export const faqsList: FAQItem[] = [
    {
      id: 'bills-of-quantities',
      question: 'What is a Bill of Quantities (BOQ)?',
      answer:
        'A Bill of Quantities is a structured document that itemizes materials, labor, and work sections required for a construction project. It enables accurate pricing by contractors and helps in tender evaluation and cost control.',
    },
    {
      id: 'contract-types',
      question: 'What types of construction contracts do you work with?',
      answer:
        'We work with various contract forms including Lump Sum, Measure & Pay, Design and Build, EPC, and FIDIC-based contracts. The appropriate contract type is selected based on project scope, client objectives, and risk allocation.',
    },
    {
      id: 'consulting-services',
      question: 'What consulting services do you provide in the construction industry?',
      answer:
        'We offer consulting services such as feasibility studies, cost planning, value engineering, contract advisory, claims & dispute resolution, procurement planning, and financial reporting for construction projects.',
    },
    {
      id: 'tendering-support',
      question: 'Do you assist companies with tendering and bid preparation?',
      answer:
        'Yes. We support clients in preparing competitive bids, developing BOQs, conducting rate analysis, reviewing tender documents, and ensuring compliance with client specifications.',
    },
    {
      id: 'site-visits',
      question: 'Do you conduct site inspections and progress valuations?',
      answer:
        'Yes. We perform routine site visits to assess work progress, verify completed activities, prepare interim valuations, and ensure quality and contract compliance.',
    },
  ];
  
  

